import type { InsertExercise } from "@shared/schema";

export const SEED_EXERCISES: InsertExercise[] = [
  // ── CHEST ───────────────────────────────────────────────────────────────────
  { name: "Barbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps", "Shoulders"]), equipment: JSON.stringify(["Barbell", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Lie on bench, grip bar slightly wider than shoulder width, lower to chest, press up." },
  { name: "Dumbbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps", "Shoulders"]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Lie on bench with dumbbells, press up to full extension, lower with control." },
  { name: "Incline Dumbbell Press", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps", "Shoulders"]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Set bench to 30-45°, press dumbbells from chest level up, emphasizing upper chest." },
  { name: "Incline Barbell Press", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps", "Shoulders"]), equipment: JSON.stringify(["Barbell", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Set bench to 30°, press barbell from upper chest, focus on upper pecs." },
  { name: "Decline Bench Press", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify(["Barbell", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Bench at decline angle, lower bar to lower chest, press up emphasizing lower pecs." },
  { name: "Cable Flyes", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Set cables at shoulder height, step forward and bring handles together in front." },
  { name: "Dumbbell Flyes", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Lie on bench, arms extended with dumbbells, lower in wide arc, squeeze back together." },
  { name: "Push-Ups", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps", "Shoulders", "Core"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "High plank position, lower chest to floor, press back up with full extension." },
  { name: "Diamond Push-Ups", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify(["Chest"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Push-up position with hands forming a diamond shape under chest." },
  { name: "Dips (Chest)", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps", "Shoulders"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Lean forward on parallel bars, lower until elbows 90°, press up. Lean forward for chest emphasis." },
  { name: "Wide Push-Ups", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Shoulders"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Push-up with hands placed wider than shoulders for more chest activation." },
  { name: "Chest Press Machine", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Seated on chest press machine, push handles forward to extension, return slowly." },
  { name: "Landmine Press", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Shoulders", "Triceps"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Barbell in landmine attachment, press upward at angle, great for shoulder-friendly chest work." },

  // ── BACK ────────────────────────────────────────────────────────────────────
  { name: "Barbell Rows", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps", "Rear Delts"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Hinge at hips, grip barbell, pull to lower chest/belly button, squeeze lats." },
  { name: "Dumbbell Rows", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "One hand on bench, pull dumbbell to hip, keep elbow close to body." },
  { name: "Pull-Ups", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Pull-up Bar"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Hang from bar with overhand grip, pull chin above bar, lower with control." },
  { name: "Chin-Ups", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Pull-up Bar"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Hang from bar with underhand grip, pull chin above bar, biceps engaged." },
  { name: "Lat Pulldown", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Sit at pulldown machine, grip bar wide, pull to upper chest, squeeze lats." },
  { name: "Cable Rows", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Seated, pull handle to navel, keep back neutral, squeeze shoulder blades." },
  { name: "Inverted Rows", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Lie under a bar, grip it, pull chest to bar while keeping body straight." },
  { name: "T-Bar Rows", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "One end of barbell anchored, straddle bar, pull loaded end to chest." },
  { name: "Deadlift", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Hamstrings", "Glutes", "Core"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Stand with feet hip-width, grip bar, drive through heels, lock out hips at top." },
  { name: "Pendlay Rows", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Strict barbell row from the floor each rep, torso parallel, explosive pull." },
  { name: "Meadows Rows", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Landmine row from side stance, overhand grip on bar end, pull to hip." },
  { name: "Straight-Arm Pulldown", primaryMuscle: "Back", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Stand at cable, arms straight, pull bar to thighs by squeezing lats." },

  // ── SHOULDERS ───────────────────────────────────────────────────────────────
  { name: "Overhead Press", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Stand with barbell at shoulders, press overhead to full extension, lower with control." },
  { name: "Dumbbell Shoulder Press", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Seated or standing, press dumbbells overhead, slight arc, full extension." },
  { name: "Arnold Press", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Start with dumbbells in front, rotate outward as you press overhead, reverse on way down." },
  { name: "Lateral Raises", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Stand with dumbbells at sides, raise to shoulder height with slight bend in elbow." },
  { name: "Front Raises", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Alternate raising dumbbells to shoulder height in front of body." },
  { name: "Rear Delt Flyes", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Back"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Bent over, raise dumbbells out to sides, squeezing rear delts at top." },
  { name: "Face Pulls", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Back", "Rear Delts"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Set cable high, pull rope to face with elbows high, external rotation at end." },
  { name: "Pike Push-Ups", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Inverted V position, lower head toward floor, press back up. Targets shoulders." },
  { name: "Handstand Push-Ups", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Triceps", "Core"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Kick up to handstand against wall, lower head to floor, press back up." },
  { name: "Cable Lateral Raises", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Cable at lowest setting, raise arm laterally to shoulder height, constant tension." },
  { name: "Upright Rows", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Traps"]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Pull barbell/dumbbells straight up along body to chin level, elbows leading." },
  { name: "Shrugs", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Traps"]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold heavy weight at sides, shrug shoulders straight up toward ears, hold at top." },

  // ── BICEPS ──────────────────────────────────────────────────────────────────
  { name: "Barbell Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Stand with barbell, curl to shoulder height, lower slowly." },
  { name: "Dumbbell Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Alternate curls with dumbbells, full range of motion, supinate at top." },
  { name: "Hammer Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify(["Forearms"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Neutral grip curl, thumbs up, targets brachialis and brachioradialis." },
  { name: "Cable Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Constant tension curls on cable machine, full range of motion." },
  { name: "Preacher Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Rest arms on preacher pad, curl weight to shoulder height, lower slowly." },
  { name: "Concentration Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Seated, elbow braced against inner thigh, curl dumbbell to shoulder, peak contraction." },
  { name: "Incline Dumbbell Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Recline on incline bench, curl dumbbells with arms hanging straight, great stretch." },
  { name: "Spider Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Chest against incline bench, arms hanging, curl dumbbells up for constant tension." },
  { name: "EZ-Bar Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify(["Forearms"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Use EZ-bar for a more wrist-friendly curl, targets both bicep heads." },

  // ── TRICEPS ─────────────────────────────────────────────────────────────────
  { name: "Close-Grip Bench Press", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify(["Chest"]), equipment: JSON.stringify(["Barbell", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Bench press with narrow grip (shoulder width), elbows close to body." },
  { name: "Tricep Pushdowns", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Stand at cable machine, push bar down to full extension, elbows fixed at sides." },
  { name: "Overhead Tricep Extension", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold dumbbell overhead with both hands, lower behind head, extend fully." },
  { name: "Skull Crushers", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Lie on bench, lower bar to forehead by bending elbows only, extend back up." },
  { name: "Tricep Dips", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify(["Chest"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Hands on bench behind you, dip down bending elbows, press back up." },
  { name: "Rope Pushdowns", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Cable with rope attachment, push down and spread rope at bottom for peak contraction." },
  { name: "Kickbacks", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Bent over, upper arm parallel to floor, extend forearm back until arm is straight." },
  { name: "JM Press", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify(["Chest"]), equipment: JSON.stringify(["Barbell", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Hybrid of close-grip bench and skull crusher, lower bar to chin area." },

  // ── QUADS ───────────────────────────────────────────────────────────────────
  { name: "Barbell Squat", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Hamstrings", "Core"]), equipment: JSON.stringify(["Barbell", "Squat Rack"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Bar on upper back, squat to parallel, drive through heels to stand." },
  { name: "Front Squat", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Core", "Glutes"]), equipment: JSON.stringify(["Barbell", "Squat Rack"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Bar on front delts, elbows high, squat upright, quad-dominant pattern." },
  { name: "Goblet Squat", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Core"]), equipment: JSON.stringify(["Kettlebells", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Hold kettlebell at chest, squat deep, elbows inside knees at bottom." },
  { name: "Bulgarian Split Squat", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Hamstrings"]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Rear foot elevated, front foot forward, squat down on front leg." },
  { name: "Leg Press", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Hamstrings"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Seated in machine, feet on platform, press until nearly extended, lower slowly." },
  { name: "Hack Squat", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Bar behind legs, squat down, drive through quads." },
  { name: "Leg Extensions", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Seated on leg extension machine, extend legs fully, squeeze quads at top." },
  { name: "Pistol Squats", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Core"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Single-leg squat to full depth, other leg extended forward." },
  { name: "Jump Squats", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Calves"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight", "Performance"]), isCompound: true, instructions: "Squat down, explode up into a jump, land softly, immediately squat again." },
  { name: "Walking Lunges", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Hamstrings"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training", "Bodyweight"]), isCompound: true, instructions: "Step forward into lunge, lower back knee toward floor, drive through front heel to next step." },
  { name: "Reverse Lunges", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training", "Bodyweight"]), isCompound: true, instructions: "Step backward into lunge position, easier on knees than forward lunges." },
  { name: "Wall Sits", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Back flat against wall, slide down to 90°, hold position for time." },
  { name: "Sissy Squats", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lean back while bending knees forward, keeping hips extended, intense quad isolation." },

  // ── HAMSTRINGS ──────────────────────────────────────────────────────────────
  { name: "Romanian Deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify(["Glutes", "Back"]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Hinge at hips with soft knees, lower bar along legs to shin level, squeeze glutes to stand." },
  { name: "Nordic Curl", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Kneel with feet anchored, slowly lower body using hamstrings, push up with hands." },
  { name: "Leg Curls", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Lying or seated on leg curl machine, curl heels toward glutes, squeeze at top." },
  { name: "Good Mornings", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify(["Back", "Glutes"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Bar on back, hinge at hips keeping legs nearly straight, return to upright." },
  { name: "Single-Leg RDL", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify(["Glutes", "Core"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Stand on one leg, hinge forward with weight, back leg extends behind for balance." },
  { name: "Stiff-Leg Deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify(["Back", "Glutes"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Like RDL but with straighter legs, deeper stretch on hamstrings." },

  // ── GLUTES ──────────────────────────────────────────────────────────────────
  { name: "Hip Thrust", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Hamstrings"]), equipment: JSON.stringify(["Barbell", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Upper back on bench, bar over hips, drive hips up to full extension, squeeze glutes." },
  { name: "Glute Bridge", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Hamstrings"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lie on back, feet flat, drive hips up, hold at top, lower." },
  { name: "Step-Ups", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Quads"]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training", "Bodyweight"]), isCompound: true, instructions: "Step up onto bench with one foot, drive through heel, bring other foot up, step down." },
  { name: "Sumo Deadlift", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Quads", "Hamstrings", "Back"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Wide stance, toes pointed out, grip bar inside knees, pull by driving hips forward." },
  { name: "Cable Pull-Throughs", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Hamstrings"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Face away from low cable, hinge at hips, pull through legs by squeezing glutes." },
  { name: "Kettlebell Swings", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Hamstrings", "Back", "Core"]), equipment: JSON.stringify(["Kettlebells"]), workoutTypes: JSON.stringify(["Weight Training", "Performance"]), isCompound: true, instructions: "Hip hinge pattern, drive hips forward to swing kettlebell to shoulder height." },
  { name: "Fire Hydrants", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "On all fours, lift knee out to side keeping 90° bend, squeeze at top." },
  { name: "Donkey Kicks", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "On all fours, drive one foot up toward ceiling, keep knee bent, squeeze glute at top." },

  // ── CALVES ──────────────────────────────────────────────────────────────────
  { name: "Standing Calf Raises", primaryMuscle: "Calves", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Stand with balls of feet on edge, raise heels high, lower below platform level." },
  { name: "Seated Calf Raises", primaryMuscle: "Calves", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Seated with weight on knees, raise and lower heels. Targets soleus." },
  { name: "Bodyweight Calf Raises", primaryMuscle: "Calves", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Stand on one or two feet, raise onto toes, lower slowly. Pause at top." },
  { name: "Jump Rope", primaryMuscle: "Calves", secondaryMuscles: JSON.stringify(["Core", "Shoulders"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight", "Performance"]), isCompound: false, instructions: "Jump rope continuously, stay on balls of feet, wrists driving the rope." },

  // ── CORE ────────────────────────────────────────────────────────────────────
  { name: "Plank", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Shoulders"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Forearm plank position, keep body rigid, breathe evenly, maintain for time." },
  { name: "Hanging Leg Raises", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Pull-up Bar"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Hang from bar, raise legs to 90° or higher, lower slowly, avoid swinging." },
  { name: "Mountain Climbers", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Shoulders"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight", "Performance"]), isCompound: false, instructions: "High plank, alternate driving knees to chest rapidly. Keep hips level." },
  { name: "Ab Wheel Rollout", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Shoulders", "Back"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Kneel with ab wheel, roll forward until body extended, pull back using core." },
  { name: "Russian Twists", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Bodyweight", "Weight Training"]), isCompound: false, instructions: "Seated with torso leaned back, rotate side to side with weight for oblique work." },
  { name: "Cable Woodchops", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Shoulders"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Cable at high or low setting, rotate diagonally across body, anti-rotation core work." },
  { name: "Dead Bug", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lie on back, arms up, alternate extending opposite arm and leg while keeping back flat." },
  { name: "Bicycle Crunches", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "On back, alternate bringing elbow to opposite knee in cycling motion." },
  { name: "Pallof Press", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Bands", "Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Stand perpendicular to cable, press handle straight out, resist rotation." },
  { name: "V-Ups", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lie flat, simultaneously raise legs and torso, reach hands to toes." },
  { name: "Side Plank", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Balance on forearm and side of foot, keep body straight, hold for time. Targets obliques." },
  { name: "Dragon Flags", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Bench"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lie on bench holding behind head, raise entire body straight, lower with control." },
  { name: "Toes to Bar", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Pull-up Bar"]), workoutTypes: JSON.stringify(["Bodyweight", "Performance"]), isCompound: false, instructions: "Hang from bar, swing legs up to touch bar with toes, using core control." },
  { name: "Turkish Get-Up", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Shoulders", "Glutes"]), equipment: JSON.stringify(["Kettlebells", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Lying down with weight overhead, progress through standing position and back down." },

  // ── FOREARMS ────────────────────────────────────────────────────────────────
  { name: "Wrist Curls", primaryMuscle: "Forearms", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Forearms on bench, curl wrists up with barbell/dumbbells, palms up." },
  { name: "Reverse Wrist Curls", primaryMuscle: "Forearms", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Forearms on bench, palms down, extend wrists up against resistance." },
  { name: "Farmer's Walk", primaryMuscle: "Forearms", secondaryMuscles: JSON.stringify(["Core", "Shoulders", "Back"]), equipment: JSON.stringify(["Dumbbells", "Kettlebells"]), workoutTypes: JSON.stringify(["Weight Training", "Performance"]), isCompound: true, instructions: "Hold heavy weights at sides, walk with upright posture for distance or time." },
  { name: "Dead Hang", primaryMuscle: "Forearms", secondaryMuscles: JSON.stringify(["Back", "Shoulders"]), equipment: JSON.stringify(["Pull-up Bar"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Hang from bar with straight arms for as long as possible. Grip and shoulder health." },

  // ── PERFORMANCE ─────────────────────────────────────────────────────────────
  { name: "Box Jumps", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Calves"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance", "Bodyweight"]), isCompound: true, instructions: "Stand before box, squat slightly, explode up landing softly on box, step down." },
  { name: "Burpees", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Chest", "Quads", "Shoulders"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance", "Bodyweight"]), isCompound: true, instructions: "Drop to push-up, do push-up, jump feet to hands, jump up with arms overhead." },
  { name: "Broad Jumps", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Hamstrings"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance", "Bodyweight"]), isCompound: true, instructions: "Stand with feet shoulder-width, swing arms, jump forward as far as possible, land soft." },
  { name: "Battle Ropes", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Core", "Back"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Alternate or simultaneous waves with ropes, maintain athletic stance throughout." },
  { name: "Sled Push", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Core"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Push loaded sled forward with low drive angle, powerful leg extension each step." },
  { name: "Sprint Intervals", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Hamstrings", "Calves", "Core"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Sprint 20-40 meters at max effort, walk back, repeat. Explosive speed training." },
  { name: "Agility Ladder", primaryMuscle: "Calves", secondaryMuscles: JSON.stringify(["Quads", "Core"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Quick feet drills through agility ladder — in-in-out, lateral shuffles, ickey shuffle." },
  { name: "Medicine Ball Slams", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Shoulders", "Back"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Lift ball overhead, slam it to ground with full body power, catch on bounce." },
  { name: "Clean and Press", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Quads", "Back", "Core"]), equipment: JSON.stringify(["Barbell", "Kettlebells"]), workoutTypes: JSON.stringify(["Weight Training", "Performance"]), isCompound: true, instructions: "Pull weight from floor to shoulders in one explosive motion, then press overhead." },
  { name: "Power Clean", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Quads", "Shoulders", "Core"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training", "Performance"]), isCompound: true, instructions: "Explosive pull from floor, catch bar in front rack position at shoulders." },
  { name: "Snatch", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Back", "Quads", "Core"]), equipment: JSON.stringify(["Barbell", "Kettlebells"]), workoutTypes: JSON.stringify(["Weight Training", "Performance"]), isCompound: true, instructions: "Single explosive movement from floor to overhead with wide grip." },
  { name: "Thrusters", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Shoulders", "Core"]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training", "Performance"]), isCompound: true, instructions: "Front squat into overhead press in one fluid movement. Full body burner." },
  { name: "Man Makers", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Chest", "Back", "Shoulders", "Quads"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Push-up, renegade row each side, jump feet in, clean and press. Full body combo." },
  { name: "Bear Crawls", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Shoulders", "Quads"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance", "Bodyweight"]), isCompound: true, instructions: "Hands and feet on ground, knees hovering, crawl forward keeping back flat." },
  { name: "Plyo Push-Ups", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps", "Shoulders"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance", "Bodyweight"]), isCompound: true, instructions: "Explosive push-up where hands leave the ground at the top, land softly." },

  // ── CHEST (additional) ──────────────────────────────────────────────────────
  { name: "Decline Dumbbell Press", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Set bench to decline angle, press dumbbells from lower chest upward, emphasizing lower pecs." },
  { name: "Pec Deck Flyes", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Sit at pec deck machine, press handles together in front of chest, squeeze at peak." },
  { name: "Cable Crossover", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Shoulders"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Stand between two cables set high, pull handles down and together crossing at waist level." },
  { name: "Svend Press", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold two plates together with palms, press outward keeping constant inward squeeze. Excellent chest isolation." },
  { name: "Dumbbell Pullover", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Back", "Triceps"]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Lie across bench, hold dumbbell overhead with both hands, lower behind head in arc, return to start." },
  { name: "Close-Grip Push-Ups", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Push-up with hands shoulder-width or closer, more tricep activation than standard push-up." },
  { name: "Incline Cable Flyes", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Incline bench between low cables, arc handles up and together overhead, targeting upper chest." },

  // ── BACK (additional) ───────────────────────────────────────────────────────
  { name: "Rack Pulls", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Hamstrings", "Glutes", "Core"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Deadlift from pins set at knee height — overloads the upper portion of the pull. Great for building back thickness." },
  { name: "Trap Bar Deadlift", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Quads", "Glutes", "Hamstrings"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Stand inside hex bar, grip neutral handles, drive through legs to lockout. More quad-friendly than straight bar." },
  { name: "Wide-Grip Pull-Up", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Pull-up Bar"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Grip bar wider than shoulders, pull chest toward bar emphasizing lat width. Harder on biceps at bottom." },
  { name: "Neutral-Grip Pull-Up", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Pull-up Bar"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Use parallel handles with palms facing each other, full pull-up. Easiest pull-up variation for most people." },
  { name: "Chest-Supported Row", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps", "Rear Delts"]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Lie face-down on incline bench, row dumbbells toward hips, eliminating lower back fatigue." },
  { name: "Ring Rows", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Hang under gymnastic rings with straight body, pull chest to rings. Difficulty adjusted by foot position." },
  { name: "Single-Arm Cable Row", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Seated or standing, pull cable handle to side with single arm, allows greater range of motion and stretch." },
  { name: "Seated Cable Row Wide Grip", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Rear Delts"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Use long bar attachment, pull wide to upper chest with elbows flared out. Hits upper back and rear delts." },

  // ── SHOULDERS (additional) ──────────────────────────────────────────────────
  { name: "Machine Shoulder Press", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Seated at shoulder press machine, press handles overhead to full extension, lower to starting position." },
  { name: "Kettlebell Press", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Triceps", "Core"]), equipment: JSON.stringify(["Kettlebells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Clean kettlebell to rack position, press overhead rotating wrist at top. Requires more stability than dumbbells." },
  { name: "Bradford Press", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Triceps"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Alternate pressing barbell over and behind head without full lockout. Continuous shoulder tension throughout." },
  { name: "Reverse Pec Deck", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Back"]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Face the pec deck, reverse grip or straight arms, pull handles back to open chest, squeezing rear delts." },
  { name: "Y-T-W Raises", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Back"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Bent over with light dumbbells, raise arms into Y, T and W shapes targeting all three parts of rear delts." },
  { name: "Plate Raise", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold weight plate at 3 and 9 o'clock, raise to eye level with straight arms. Great front delt isolation." },
  { name: "Half-Kneeling Landmine Press", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Core", "Triceps"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Kneel with barbell in landmine, press at upward angle. Shoulder-friendly alternative to overhead pressing." },
  { name: "Dumbbell Cuban Press", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Upright row into external rotation into overhead press. Excellent rotator cuff and shoulder health exercise." },
  { name: "Cable External Rotation", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Side-on to cable, elbow bent 90° at side, rotate forearm outward. Essential rotator cuff strengthening." },

  // ── BICEPS (additional) ─────────────────────────────────────────────────────
  { name: "Cross-Body Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify(["Forearms"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Curl dumbbell across body to opposite shoulder with neutral grip. Targets brachialis and long head." },
  { name: "Zottman Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify(["Forearms"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Curl up with supinated grip, rotate to pronated at top, lower in reverse curl. Hits all elbow flexors." },
  { name: "Reverse Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify(["Forearms"]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Overhand (pronated) grip curl. Develops brachialis and brachioradialis for thicker arm appearance." },
  { name: "Drag Curls", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Instead of arcing the bar out, drag it up along your torso with elbows going back. Peak bicep contraction." },
  { name: "21s", primaryMuscle: "Biceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "7 reps bottom-half, 7 reps top-half, 7 reps full range. Intense time-under-tension bicep burner." },

  // ── TRICEPS (additional) ────────────────────────────────────────────────────
  { name: "Tate Press", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells", "Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Lie on bench, dumbbells above chest elbows flared out, fold forearms down touching chest, press back up." },
  { name: "French Press", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Seated or lying, hold EZ-bar or dumbbells overhead, bend elbows lowering weight behind head, extend." },
  { name: "Cable Overhead Tricep Extension", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Face away from high cable, lean forward, extend forearms overhead keeping elbows fixed. Great long-head stretch." },
  { name: "Single-Arm Tricep Pushdown", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Single-arm pushdown allows full pronation and peak contraction at the bottom. Corrects imbalances." },
  { name: "Reverse Grip Pushdown", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Use underhand (supinated) grip on cable bar, push down to lockout. Hits lateral head very effectively." },
  { name: "Tricep Press Machine", primaryMuscle: "Triceps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Seated dip machine or plate-loaded tricep machine, press arms to full extension, squeeze at bottom." },

  // ── QUADS (additional) ──────────────────────────────────────────────────────
  { name: "Box Squat", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Hamstrings"]), equipment: JSON.stringify(["Barbell", "Squat Rack"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Squat back to box, pause sitting on it, then drive up explosively. Teaches proper hip hinge and depth." },
  { name: "Pause Squat", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Core"]), equipment: JSON.stringify(["Barbell", "Squat Rack"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Descend into squat, pause 2–3 seconds at bottom, stand up. Eliminates stretch reflex, builds raw strength." },
  { name: "Zercher Squat", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Core", "Back", "Glutes"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Bar held in the crooks of your elbows in front. Extreme core demand, great upright posture squat." },
  { name: "Smith Machine Squat", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes"]), equipment: JSON.stringify(["Squat Rack"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Squat inside Smith machine — fixed bar path allows more foot placement experimentation and added safety." },
  { name: "Barbell Lunge", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Hamstrings"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Bar on back, step forward into lunge, lower back knee to floor, drive through front foot to return." },

  // ── HAMSTRINGS (additional) ─────────────────────────────────────────────────
  { name: "Lying Leg Curl", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Lie face-down on machine, curl heels toward glutes under load, squeeze at top." },
  { name: "Seated Leg Curl", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Sit upright, pad over thighs, curl heels down. Allows greater range of motion than lying version." },
  { name: "Cable Leg Curl", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Attach ankle cuff to low cable, stand facing machine, curl heel toward glute. Good for constant tension." },
  { name: "Reverse Hyperextension", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify(["Glutes", "Back"]), equipment: JSON.stringify(["Bench"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Lie on high bench with legs hanging, swing legs up using glutes and hamstrings, lower with control." },
  { name: "45-Degree Hip Extension", primaryMuscle: "Hamstrings", secondaryMuscles: JSON.stringify(["Glutes", "Back"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight", "Weight Training"]), isCompound: true, instructions: "Brace torso on 45° pad, hinge at hips lowering torso, extend back up squeezing glutes and hamstrings." },

  // ── GLUTES (additional) ─────────────────────────────────────────────────────
  { name: "Banded Glute Bridge", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Hamstrings"]), equipment: JSON.stringify(["Bands"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Resistance band above knees, standard glute bridge. Band forces knees out, activating glute medius more." },
  { name: "Barbell Glute Bridge", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Hamstrings"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Lie on floor with heavy barbell over hips, drive hips to ceiling, pause at top. Heavier than hip thrust." },
  { name: "Frog Pumps", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lie on back, soles of feet together, knees flared out, drive hips up squeezing glutes. High-rep burnout." },
  { name: "Clamshells", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Bands"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lie on side, knees bent, feet together. Open top knee like a clamshell keeping feet together. Glute medius." },
  { name: "Lateral Band Walks", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Quads"]), equipment: JSON.stringify(["Bands"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Band above knees, quarter squat, side-step in both directions. Activates glute medius and hip abductors." },
  { name: "Cable Hip Abduction", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Stand side-on to low cable with ankle cuff, kick leg away from machine. Isolates glute medius." },

  // ── CALVES (additional) ─────────────────────────────────────────────────────
  { name: "Single-Leg Calf Raise", primaryMuscle: "Calves", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Balance on one foot on edge of step, raise onto toes, lower below step, slow and controlled." },
  { name: "Donkey Calf Raises", primaryMuscle: "Calves", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Bench"]), workoutTypes: JSON.stringify(["Bodyweight", "Weight Training"]), isCompound: false, instructions: "Bend at hips, hands on bench, raise heels with partner sitting on hips. Old-school calf mass builder." },
  { name: "Explosive Calf Jumps", primaryMuscle: "Calves", secondaryMuscles: JSON.stringify(["Quads"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance", "Bodyweight"]), isCompound: false, instructions: "Quick, low-amplitude jumps staying on balls of feet. Builds reactive calf strength and ankle stiffness." },

  // ── CORE (additional) ───────────────────────────────────────────────────────
  { name: "Cable Crunch", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Kneel at cable, rope behind head, crunch forward to bring elbows toward knees, reverse slowly." },
  { name: "Hollow Body Hold", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lie on back, press lower back to floor, lift legs and shoulders, hold hollow position for time." },
  { name: "Windmill", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Shoulders", "Glutes"]), equipment: JSON.stringify(["Kettlebells", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Hold weight overhead, feet wide, hinge and reach opposite hand to floor keeping top arm locked." },
  { name: "Weighted Sit-Ups", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold weight plate or dumbbell on chest, perform full sit-up to an upright seated position." },
  { name: "Flutter Kicks", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lie on back, legs 6 inches off floor, alternate kicking up and down. Attacks lower abs." },
  { name: "Hanging Knee Raises", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Pull-up Bar"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Hang from bar, pull knees to chest, lower slowly. Beginner-friendly lower ab exercise." },
  { name: "Scissor Kicks", primaryMuscle: "Core", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Lie on back, legs raised, cross legs over each other in alternating scissor motion keeping lower back flat." },
  { name: "Landmine Twists", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Shoulders"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold end of landmine barbell, arms extended, rotate side to side in controlled arc. Powerful oblique work." },
  { name: "Copenhagen Plank", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Glutes"]), equipment: JSON.stringify(["Bench"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "Side plank with top foot on bench, bottom leg raised. Trains hip adductors and lateral core together." },
  { name: "Bird Dog", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Back", "Glutes"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: false, instructions: "On all fours, extend opposite arm and leg simultaneously, hold, return. Builds anti-rotation core stability." },

  // ── FOREARMS (additional) ───────────────────────────────────────────────────
  { name: "Wrist Roller", primaryMuscle: "Forearms", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold roller with arms extended, roll weight up by alternating wrist flexion and extension, roll back down." },
  { name: "Plate Pinch", primaryMuscle: "Forearms", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Pinch two smooth plates together with fingers and thumb, hold for time. Builds crushing and pinch grip." },
  { name: "Towel Pull-Ups", primaryMuscle: "Forearms", secondaryMuscles: JSON.stringify(["Back", "Biceps"]), equipment: JSON.stringify(["Pull-up Bar"]), workoutTypes: JSON.stringify(["Bodyweight"]), isCompound: true, instructions: "Loop two towels over pull-up bar, grip towels and perform pull-ups. Extreme forearm and grip demand." },
  { name: "Finger Curls", primaryMuscle: "Forearms", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell", "Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Forearms on bench, let bar roll to fingertips, curl back up with fingers only. Trains finger flexors." },

  // ── TRAPS ───────────────────────────────────────────────────────────────────
  { name: "Barbell Shrugs", primaryMuscle: "Traps", secondaryMuscles: JSON.stringify(["Forearms"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold heavy barbell at thighs, shrug shoulders straight up as high as possible, hold briefly, lower." },
  { name: "Dumbbell Shrugs", primaryMuscle: "Traps", secondaryMuscles: JSON.stringify(["Forearms"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold dumbbells at sides, shrug both shoulders up simultaneously. Allows hands to travel further back than barbell." },
  { name: "Cable Shrugs", primaryMuscle: "Traps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Cable Machine"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Stand in front of low cable with straight bar, shrug upward. Cable provides constant tension through full range." },
  { name: "Power Shrugs", primaryMuscle: "Traps", secondaryMuscles: JSON.stringify(["Back", "Core"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: true, instructions: "Use leg drive to help shrug the bar higher than a strict shrug allows. Trains explosive upper trap strength." },
  { name: "Trap Bar Shrugs", primaryMuscle: "Traps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Use hex bar with neutral grip to shrug. Natural hand position removes forearm fatigue allowing heavier loads." },
  { name: "Behind-Back Barbell Shrugs", primaryMuscle: "Traps", secondaryMuscles: JSON.stringify([]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Hold barbell behind glutes, shrug upward. Hand position shifts emphasis to middle and lower traps." },
  { name: "Snatch-Grip Shrugs", primaryMuscle: "Traps", secondaryMuscles: JSON.stringify(["Shoulders"]), equipment: JSON.stringify(["Barbell"]), workoutTypes: JSON.stringify(["Weight Training"]), isCompound: false, instructions: "Wide snatch grip on barbell, shrug high with elbows leading. Develops the upper trap from a stretched position." },

  // ── PERFORMANCE (additional) ─────────────────────────────────────────────────
  { name: "Depth Jumps", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Calves"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Step off box, land and immediately explode upward. Trains reactive strength and plyometric ability." },
  { name: "Lateral Bounds", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Quads", "Calves"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance", "Bodyweight"]), isCompound: true, instructions: "Push off one foot laterally, land on the other, stick landing briefly. Builds lateral power and balance." },
  { name: "Skater Jumps", primaryMuscle: "Glutes", secondaryMuscles: JSON.stringify(["Quads", "Core"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance", "Bodyweight"]), isCompound: true, instructions: "Explosive lateral leaps side to side on one foot, mimicking speed skater stride. Hip adductor and glute power." },
  { name: "Tire Flips", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Quads", "Glutes", "Shoulders"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Drive under tire, explosive leg push to upright position, then push tire over. Full-body power movement." },
  { name: "Cone Drills", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Calves", "Core"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Sprint and change direction around a series of cones. Builds first-step quickness and change-of-direction speed." },
  { name: "Weighted Vest Push-Ups", primaryMuscle: "Chest", secondaryMuscles: JSON.stringify(["Triceps", "Shoulders"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance", "Bodyweight"]), isCompound: true, instructions: "Standard push-up wearing a weighted vest. Progressively loads the pattern without equipment." },
  { name: "TRX Rows", primaryMuscle: "Back", secondaryMuscles: JSON.stringify(["Biceps", "Core"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Bodyweight", "Performance"]), isCompound: true, instructions: "Lean back holding TRX straps, row chest to handles. Difficulty changes with body angle and foot position." },
  { name: "Sandbag Carries", primaryMuscle: "Core", secondaryMuscles: JSON.stringify(["Back", "Shoulders", "Quads"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Bear-hug or shoulder a sandbag, walk for distance. Builds functional carrying strength and grip endurance." },
  { name: "Hill Sprints", primaryMuscle: "Quads", secondaryMuscles: JSON.stringify(["Glutes", "Hamstrings", "Calves"]), equipment: JSON.stringify([]), workoutTypes: JSON.stringify(["Performance"]), isCompound: true, instructions: "Sprint up a steep incline at max effort, walk down to recover. Builds power, speed and cardiovascular capacity." },
  { name: "Dumbbell Snatch", primaryMuscle: "Shoulders", secondaryMuscles: JSON.stringify(["Back", "Quads", "Core"]), equipment: JSON.stringify(["Dumbbells"]), workoutTypes: JSON.stringify(["Weight Training", "Performance"]), isCompound: true, instructions: "Explosive single-arm pull from floor to locked overhead in one movement. Develops total-body power." },
];
